# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024–2026 Alexandre Nuernberg <alexandreberg@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""
@file config.py
@brief Centralised configuration for SAPI Darts predictive models (M4/M5).

All path resolution is relative to this file so the folder is self-contained.
No imports from predictive_model_v2/.
"""

import os

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_HERE = os.path.dirname(os.path.abspath(__file__))
_RASPBERRY = os.path.dirname(_HERE)

SYNTHETIC_DATA_DIR = os.path.join(_RASPBERRY, "predictive_synthetic_data")
"""Path to the read-only synthetic CSVs generated by predictive_model_v2/00_generate_synthetic_events.py."""

OUTPUT_DIR = os.path.join(_HERE, "output")
"""Root output directory; sub-folders model4_lgbm/ and model5_nhits/ are created at runtime."""

# ---------------------------------------------------------------------------
# Resampling
# ---------------------------------------------------------------------------

RESAMPLE_MIN = 5
"""Target time resolution in minutes (5-min grid, same as M2/M3)."""

GAP_FILL_MAX_MIN = 15
"""Maximum gap length (minutes) that is filled by linear interpolation; longer gaps stay NaN."""

# ---------------------------------------------------------------------------
# Model horizons
# ---------------------------------------------------------------------------

HORIZONS_MIN = [30, 60, 90, 120]
"""Prediction horizons in minutes. Indices inside output_chunk_length=24 at 5-min resolution:
step 5 → +30 min, step 11 → +60 min, step 17 → +90 min, step 23 → +120 min."""

HORIZON_STEP_IDX = {30: 5, 60: 11, 90: 17, 120: 23}
"""Mapping from horizon (min) to 0-based step index within a 24-step prediction vector."""

OUTPUT_CHUNK_STEPS = 24
"""Number of future steps the model predicts simultaneously (24 × 5 min = 120 min)."""

# ---------------------------------------------------------------------------
# Alert thresholds (cm) — same reference as M1/M2/M3
# ---------------------------------------------------------------------------

THRESHOLD_ATENCAO   = 90
THRESHOLD_ALERTA    = 110
THRESHOLD_INUNDACAO = 130

# ---------------------------------------------------------------------------
# Shared training hyper-parameters
# ---------------------------------------------------------------------------

RANDOM_STATE = 42

# --- LightGBM (M4) ---
LGBM_LAGS            = [-24, -18, -12, -9, -6, -3, -1]
"""Level lags (steps): −120, −90, −60, −45, −30, −15, −5 min."""

LGBM_PRECIP_LAGS     = [-18, -12, -6, -1]
"""Past-covariate (precipitation) lags: −90, −60, −30, −5 min."""

LGBM_BUFFER_STEPS    = max(abs(l) for l in LGBM_LAGS)
"""Minimum history steps required before first LightGBM prediction."""

LGBM_N_ESTIMATORS    = 500
LGBM_NUM_LEAVES      = 31

# --- N-HiTS (M5) ---
NHITS_INPUT_STEPS    = 120
"""Input chunk length for N-HiTS: 120 × 5 min = 10 h lookback."""

NHITS_N_STACKS       = 3
NHITS_N_BLOCKS       = 1
NHITS_FREQ_DOWNSAMPLE = ((8,), (4,), (1,))
"""Multi-scale pooling sizes per stack × block (coarse 40-min / medium 20-min / fine 5-min).
Darts NHiTSModel expects Tuple[Tuple[int]] — one inner tuple per stack, one int per block."""

NHITS_N_EPOCHS       = 20
"""Training epochs. Start with 20 for a quick test run; increase to 100–300 for
final thesis results (expect ~2–5 min/epoch on RPi 4 CPU)."""
NHITS_BATCH_SIZE     = 32
NHITS_LAYER_WIDTHS   = 128
"""Hidden layer width — reduced from Darts default 512 to avoid overfitting on small dataset."""
